# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Awesome City Trips' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Awesome City Trips

  # Payments
  #pod 'Stripe'

  # Reactive
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'

  # Networking
  pod 'Moya', '~> 10'
  pod 'ReachabilitySwift', '~> 4'

  # Image
  pod 'Kingfisher', '~> 4'
  
  # User Interface
  pod 'TPKeyboardAvoiding', '~> 1.3'
  pod 'ActionSheetPicker-3.0'
  
  # Alerts & Animation
  pod 'KVNProgress', '~> 2'
  pod 'NVActivityIndicatorView', '~> 4'

  # Crash Reporting & Analytics
  #pod 'Fabric'
  #pod 'Crashlytics'
  #pod 'FacebookCore'
  
  # Backend
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Crash'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  # Localization
  pod 'PolyglotLocalization'

  # Security
  pod 'KeychainAccess', '~> 3'

  # Util
  pod 'SwiftLint'
  pod 'DeviceKit', '~> 1'

  target 'Awesome City TripsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Awesome City TripsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
